name: Build Wheel, Release on GitHub/PyPI, and Deploy Docs

on:
  workflow_dispatch:
  push:
    tags:
      - "*" # Trigger on all tags initially, but tag and release privilege are verified in _build-wheel-release-upload.yml

jobs:
  build-release:
    uses: scikit-package/release-scripts/.github/workflows/_build-wheel-release-upload.yml@v0
    with:
      project: ufpdf-xfel-scripts
      c_extension: false
      maintainer_GITHUB_username: luisLkitsu, sbillinge
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
